@startuml
title Principio de Segregación de Interfaces (ISP) - Refactorización

interface IColaborador {
    +colaborarEnProyecto()
}

interface IGestor {
    +asignarTareas()
    +revisarProgreso()
}

class Administrador {
    +crearProyecto()
    +cerrarProyecto()
}

class ResponsableProyecto {
    +actualizarEstadoEtapa()
}

class Diseñador {
    +diseñarMaterialAudiovisual()
}

Administrador ..|> IGestor
Administrador ..|> IColaborador

ResponsableProyecto ..|> IGestor
ResponsableProyecto ..|> IColaborador

Diseñador ..|> IColaborador

@enduml
